- name: Create EC2 Instance
  hosts: localhost
  tasks:
    - ec2:
        key_name: test
        instance_type: t2.micro
        image: ami-0f65671a86f061fcd
        wait: yes
        group: mysecgroup 
        count: 3
        vpc_subnet_id: subnet-c33c268e
        assign_public_ip: yes
        region: us-east-2
      register: out
   
    - debug:
        msg: "{{out}}"
    - add_host:
        hostname: "{{item.public_ip}}"
        groupname: myservers
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/aws/ueokey.pem
        ansible_python_interpreter: /usr/bin/python3
      with_items: "{{out.instances}}"

    - wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 30
        timeout: 320
        state: started
      with_items: "{{ out.instances }}"

- name: setup user
  hosts: myservers
  become: yes
  tasks:
    - name: install git
      package:
        name: git
        state: installed
    - name: clone git repo
      shell: git clone https://github.com/lerndevops/scritps.git
      args:
        chdir: /tmp
    - name: create user
      shell: /tmp/scritps/setup-aws-user.sh
      register: outt
    - debug:
        var: outt
